server:
  port: 8020

spring:
  application:
    name: microservicloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/buerbl/learnSpringCloud.git
          username: @@@@@163.com
          password: @@@



