server:
  port: 7001

eureka:
  instance:
    hostname: localhost # eureka 服务端的实例名称
  client:
    register-with-eureka: false # 表示不需要向注册中心注册自己
    fetch-registry: false # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${service.port}/eureka/ # 设置与 Eureka Server 交互的地址查询服务和注册服务